### ISSUE TITLE
Cannot read properties of undefined (reading 'formatString')

### ISSUE THREAD

**Issue by SirHoDo** [Arny4/Afk-Bot#72]
FIXED THIS ISSUE BY DELETING package-lock.json

urFate, please add package-lock.json to .gitignore

**Comment by urFate** [comment]
[Adding `package-lock.json` to ignore list is not advised and can cause more problems.](https://www.google.com/search?q=should+be+package-lock.json+included+in+git+repo) Your solution is workaround and not fix of this issue. Can you upload full log instead?
